### ISSUE TITLE
Scores on a MSA

### ISSUE THREAD

**Issue by damiano-sg** [spetti/SSW-and-GRUMLIN#1]
Hi,
Your work is really interesting and I don't really have any issue to report but I just have a question on how that works.
Is your model also able to score new sequences given a fixed aligment ? I'm thinking of something similar to the function `hmmsearch` of HMMER which searches a sequence against a given `.hmm` model. If so, how can I do that ? Reading your paper I can't really see if something like that it is possible or not.

I wonder whether you have any option to search a sequence against an MSA and give it a score which reflects how well the sequence is described by the model MSA. From my point of view this might be a really interesting functionality.  For instance it could allow us to compare two different alignments of sequences from the same family.
Thanks a lot for your time and your work !

**Comment by sokrypton** [comment]
We don't try this in the manuscript, but technically, the learned convolutions of a given protein family can then be used to construct an alignment of the new sequence to SUMRF. The sitewise and pairwise parameters can be used to compute a pLL for the new sequence.

**Comment by damiano-sg** [comment]
Ok great ! Thank you very much.
