### ISSUE TITLE
Question about results interpretation

### ISSUE THREAD

**Issue by brendanofallon** [spetti/SSW-and-GRUMLIN#2]
Hi there, really amazing work on this. Just a question about how to interpret the results matrix of an alignment. In the examples it says element i,j is the probability of item i from sequence 1 being aligned to item j of sequence 2, which makes sense to me. However the sums of the rows and columns are less than one -  so would it be correct to say that the remaining probability is the probability of there being a gap in the alignment there? For instance, if row i has a sum of 0.75, there's a 25% of element i being aligned to a gap in the other sequence?

**Comment by sokrypton** [comment]
That is correct!
